Inscription:
    type: entity
    table: inscription
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cin:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: CIN
        cne:
            type: string
            nullable: true
            length: 12
            fixed: false
            comment: ''
            column: CNE
        nom:
            type: string
            nullable: true
            length: 65
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: true
            length: 65
            fixed: false
            comment: ''
        email:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        adresse:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        telMobile:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: tel_mobile
        telFixe:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: tel_fixe
        noteS1:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: note_s1
        noteS2:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: note_s2
        noteS3:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: note_s3
        noteS4:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: note_s4
        noteS5:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: note_s5
        noteS6:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: note_s6
        filiere1:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
            column: filiere_1
        filiere2:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
            column: filiere_2
        filiere3:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
            column: filiere_3
        filiere4:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
            column: filiere_4
        filiere5:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
            column: filiere_5
    lifecycleCallbacks: {  }
