parameters:
#    bse_inscription.example.class: Bse\InscriptionBundle\Example

services:
#    bse_inscription.example:
#        class: %bse_inscription.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
